### ISSUE TITLE
[how-to] Mount Jenkins agent .m2 in devcontainer

### ISSUE THREAD

**Issue by ngsoftwaredev** [felipecrs/docker-images#134]
Hi,

I'm using `devcontainer` in a Jenkins pipeline:

```
docker.build('devcontainer-agent', ".devcontainer")
                            .inside('--volume=/var/run/docker.sock:/var/run/docker.sock --network=host --group-add=docker -e TZ=Europe/Paris') {
        sh """
            mvn -s settings.xml clean deploy
            docker build -t local/my-webapp:latest --build-arg SERVER_PORT=8080 -f ./my-webapp/Dockerfile ./data-crud-service-webapp
        """
        }
```

My `.devcontainer/Dockerfile` looks like this:

```
FROM ghcr.io/felipecrs/devcontainer

RUN pkgx install openjdk.org@17 maven.apache.org@3 \
    && java --version \
    && mvn --version

```

I'd like to add a volume mount to the Docker command, adapted from the Jenkins documentation, so that I avoid redownloading dependencies between runs, something like `-v $HOME/.m2:/root/.m2`.

Where in the contained should I mount the agent's _.m2_ directory? I've made several attempts but could not get it to work...

**Comment by felipecrs** [comment]
`HOME` within devcontainer is `/home/devcontainer`, so the m2 should be at `/home/devcontainer/.m2`. Have you tried it?

**Comment by ngsoftwaredev** [comment]
Hi, thanks for your answer. Yes I tried it, but then maven can't create subdirectories in _/home/devcontainer/.m2_, even if I force the volume mount as read-write...

**Comment by felipecrs** [comment]
I'm trying to test this.

**Comment by felipecrs** [comment]
I just added a test to verify that this works:

https://github.com/felipecrs/docker-images/blob/629ab4e916fa452c345177f8629d1d68d630b392/jenkins-agent-dind/test-fixtures/jobs/test-agent-scripted/Jenkinsfile

And it's working.

I believe in your case, the `~/.m2` folder in your Jenkins Agent is write-protected by some rule.

Can you `stat ~/.m2` within and without the container and paste here the output?

**Comment by ngsoftwaredev** [comment]
Hi, I ran some tests and it turns out the managed Jenkins we are using doesn't even have Maven installed on the agents...

Sorry to have bothered you, and many thanks for your reactivity!

**Comment by felipecrs** [comment]
Turns out I could reproduce this issue when running devcontainer itself inside of jenkins-agent-dind, and 52531cc85ded6ff497666ef671dc4f072b671ffd fixed it.
